"""baseline schema

Revision ID: 68e27f62dd30
Revises: 
Create Date: 2026-08-13 19:04:00.410913

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

raw_file_type_enum = postgresql.ENUM(
    'AUDIO', 'TRANSCRIPT_PROVIDED', 'TRANSCRIPT_GENERATED', name='raw_file_type'
)


# revision identifiers, used by Alembic.
revision: str = '68e27f62dd30'
down_revision: Union[str, None] = '74252ed682e8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('group_members', sa.Column('embedding', sa.JSON(), nullable=True))
    op.add_column('group_members', sa.Column('embedding_audio_path', sa.String(length=255), nullable=True))
    op.add_column('group_members', sa.Column('embedding_updated_at', sa.DateTime(), nullable=True))
    op.alter_column('group_members', 'name',
               existing_type=sa.VARCHAR(length=45),
               type_=sa.String(length=255),
               existing_nullable=True)
    op.alter_column('groups', 'name',
               existing_type=sa.VARCHAR(length=45),
               type_=sa.String(length=255),
               existing_nullable=True)
    op.add_column('raw_files', sa.Column('processed_date', sa.DateTime(), nullable=True))
    raw_file_type_enum.create(op.get_bind(), checkfirst=True)
    op.add_column('raw_files', sa.Column('type', raw_file_type_enum, nullable=False))
    op.add_column('raw_files', sa.Column('status', sa.Text(), nullable=True))
    op.drop_column('raw_files', 'raw_file_type')
    op.alter_column('users', 'username',
               existing_type=sa.VARCHAR(length=45),
               type_=sa.String(length=255),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'username',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=45),
               existing_nullable=True)
    op.add_column('raw_files', sa.Column('raw_file_type', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('raw_files', 'status')
    op.drop_column('raw_files', 'type')
    raw_file_type_enum.drop(op.get_bind(), checkfirst=True)
    op.drop_column('raw_files', 'processed_date')
    op.alter_column('groups', 'name',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=45),
               existing_nullable=True)
    op.alter_column('group_members', 'name',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=45),
               existing_nullable=True)
    op.drop_column('group_members', 'embedding_updated_at')
    op.drop_column('group_members', 'embedding_audio_path')
    op.drop_column('group_members', 'embedding')
    # ### end Alembic commands ###
