"""add summary to meetings

Revision ID: a71cbeb0ac72
Revises: b3cdbaa22a65
Create Date: 2026-08-29 00:00:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a71cbeb0ac72'
down_revision: Union[str, None] = 'b3cdbaa22a65'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('meetings', sa.Column('summary', sa.Text(), nullable=True))
    op.add_column('meetings', sa.Column('summary_generated_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('meetings', 'summary_generated_at')
    op.drop_column('meetings', 'summary')
    # ### end Alembic commands ###
