"""add repo and board to groups

Revision ID: b3cdbaa22a65
Revises: 455a31a662c9
Create Date: 2026-08-13 19:44:08.649887

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b3cdbaa22a65'
down_revision: Union[str, None] = '455a31a662c9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('groups', sa.Column('github_repo_url', sa.String(length=512), nullable=True))
    op.add_column('groups', sa.Column('trello_board_id', sa.String(length=24), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('groups', 'trello_board_id')
    op.drop_column('groups', 'github_repo_url')
    # ### end Alembic commands ###
