"""hello world

Revision ID: d6d52e866222
Revises: 0001_hello_world
Create Date: 2025-09-05 14:50:00.925877

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd6d52e866222'
down_revision: Union[str, None] = '0001_hello_world'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute(
        "ALTER TABLE raw_files ALTER COLUMN type TYPE raw_file_type USING type::raw_file_type"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('raw_files', 'type',
               existing_type=sa.Enum('AUDIO', 'TRANSCRIPT_PROVIDED', 'TRANSCRIPT_GENERATED', name='raw_file_type'),
               type_=sa.VARCHAR(length=255),
               existing_nullable=False)
    # ### end Alembic commands ###
